server:
  port: 8088

spring:
  application:
    name: AstroTalk
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgresql}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    url: ${SPRING_DATASOURCE_URL:eltacqeferli@gmail}
  liquibase:
    enabled: true

admin:
  email: ${ADMIN_EMAIL}

