server:
  port: 8088

spring:
  application:
    name: AstroTalk
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgresql}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://35.223.201.116:5432/astro}
  liquibase:
    enabled: true

  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
    web:
      resources:
        static-locations: file:src/main/resources/static/

admin:
  email: ${ADMIN_EMAIL:eltacqeferli@gmail.com}

file:
  storage:
    path: /app/static

